version: 3.1.1

services:
  postgres:
    build: docker/services/postgres
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - '/opt/volumes/local/postgres/data:/var/lib/postgresql/data'
    env_file:
      - docker/env/postgres.env
    networks:
      - dev-estacio-network

networks:
  dev-estacio-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.100.0.0/16