server:
  #port: 8080
  servlet:
    context-path: /financas/api

### Spring settings
spring:
  application:
    name: finances

  # DATABASE
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://junction.proxy.rlwy.net:45731/railway}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:EgzfXkYxzsOOgwxsDdNUDwbWDWPPGZqz}
    driver-class-name: org.postgresql.Driver

  # JPA
  jpa:
    hibernate:
      ddl-auto: none
    #database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # JACKSON
  jackson:
    deserialization:
      fail-on-unknown-properties: true

#  security:
#    jwt:
#      secret: ${SECURITY_JWT_SECRET:Frrlo0VY6KWhn3MMYVUpTQEwY7KF8a2a}
#      expiration: ${SECURITY_JWT_EXPIRATION:3600}